- src/js/owl.carousel.js
Because IE7 does not support the latter one.
> Use `charAt(0)` instead of `[0]`

- src/js/owl.autoheight.js
Demo
---------
before: http://dimmy.pro/autoheight/before/
after: http://dimmy.pro/autoheight/after/
Screenshots
---------
before: http://my.jetscreenshot.com/7945/20141027-3g7l-156kb.jpg
after: http://my.jetscreenshot.com/7945/20141027-zwin-181kb.jpg
> Multiple items support for autoheight plugin

- docs_src/templates/pages/docs/started-faq.hbs
- docs_src/templates/pages/docs/support-contact.hbs
- docs_src/templates/pages/docs/support-contributing.hbs
- package.json
* Updates email address to Smashing Boxes support email, opensource@smashingboxes.com.
* Updates `package.json` to point to smashingboxes/OwlCarousel2 rather than OwlFonk/OwlCarousel2.
> Updates support email to smashing boxes opensource email.

- src/css/owl.animate.css
- src/js/owl.hash.js
- src/js/owl.navigation.js
This is not a pull to formally introduce jquery 1.9+ support, however the only current blocker seems to be complying with this deprecation.  This should change no functionality of implementation of the api.
See http://jquery.com/upgrade-guide/1.9/#addback-selector-replaces-andself- for more details
> change instances of .andSelf to .addBack to comply with the jquery 1.9+ 

- Gruntfile.js
- package.json
- test/index.html
Adds test coverage information at build time. By default, when running grunt, it will only show the test coverage percentage if a file falls below the threshold.  If grunt is run with the `--verbose` flag, it will show the coverage percentage for every file that is tested.
At the moment, the pass threshold is set to 0%. I don't think our test coverage is robust enough at the moment to be failing builds because there aren't enough tests (the support module is at 100% and the main module is at 61%, but all other modules are 0%).
> Build: Adds blanket.js to provide test coverage information at build time (Ref #906)

- docs_src/templates/pages/docs/started-installation.hbs
Update the getting started page to clarify that owl-theme is required in order to have nav controls.
> Update the getting started page

- src/js/owl.autoheight.js
It simply threw an error when we use ``autoHeight`` because ``height`` is not defined
> Fix syntax error in strict mode

- docs_src/data/options.json
> Fix a typo

- src/js/owl.lazyload.js
This fixes the scenario where you try to lazy load index 0 from a change event (e.g. when `startPosition` is 1).
0 is falsy so `position` was being set as `this._core.current()` instead of `e.property.value`.
> Fix lazy loading position 0

- src/scss/owl.lazyload.scss
The transform-style property should probably only be applied if using the owl-lazy load class.
> Fixed when transform property is applied

- src/js/owl.support.modernizr.js
fix transitionend support detection, which does not work properly for older Android versions,
as it does not give the prefixed event name.
see the following links for details:
https://github.com/Modernizr/Modernizr/issues/897
https://github.com/niksy/modernizr-detects/commit/05d148fc4f3813b1412c836325a9ca78c7a63f4d
fixes #514
> fix transitionend support detection for Android 4.[1-3]

- src/js/owl.linked.js
On line 94 of the code, instead of Linked, there was a undefined Sync variable, probably from OwlCarousel Sync plugin code.
The Sync variable was switched to Linked.
> Sync switched to Linked

- package.json
The engine flag should be either removed or updated. Since this is a package for the browser, I'd say remove it since it isn't really relevant.
Creating this PR since yarn throws an error if the engine is incompatible.
https://github.com/yarnpkg/yarn
> Remove engine from package.json

- CONTRIBUTING.md
- docs_src/templates/pages/docs/started-faq.hbs
- docs_src/templates/pages/docs/support-contact.hbs
Some emails and links point at dead URLs.
- Removed old email from documentation
- Fixed URLs in Contributing guidelines to point at current GitHub URL
> Remove references to old maintainer from documentation

- src/js/owl.carousel.js
Hi... I'm receiving a lot of error event in Sentry about `Uncaught Can not detect viewport width.`.
I would suggest to not throw an error since users can't do anything about this. Also, It will use up my error reporting quota. 
How about print a console warning or error though?
https://github.com/OwlCarousel2/OwlCarousel2/issues/1704
> Fixes detect viewport method to use warn instead throw

- src/js/owl.carousel.js
- src/js/owl.navigation.js
1. Navigation.prototype.destroy() destroys users' custom `navContainer` erroneously.
2. Owl.prototype.destroy() fails to remove `owl-stage`.
closes #1768
> fix two problems related to destroy

- src/js/owl.carousel.js
This is a bit of an edge case, but it is possible to set the [`items` options](https://owlcarousel2.github.io/OwlCarousel2/docs/api-options.html) to a fractional number (e.g. 2.5 items per page instead of 3). This actually works well, except for these lines here. For example, if `items` is set to 2.5, and there are 4 images in the carousel, then `repeat` becomes 1.5. The first `repeat--` makes `repeat` equal .5, then the next loop `repeat` equals -.5. Because the loop is supposed to terminate when `repeat` is 0 (falsy), the loop instead continues to run, and `repeat` goes down to negative infinity. Eventually the browser runs out of memory with strange errors (Chrome just says "Invalid string length"). The proposed change fixes this problem.
> Fix infinite loop

- docs/docs/api-events.html
- docs_src/data/events.json
Changed word from 'postion' to 'position'.
> Fix typos in events.json and api-events.html

- package.json
Adding this field, npm modules like [sass-module-importer](https://www.npmjs.com/package/sass-module-importer) or [npm-css](https://www.npmjs.com/package/npm-css) can import the CSS from the Owl Carousel `npm_modules` folder.
EG.
`@import 'owl-carousel';`
NOTE - this is not standardised, but is widely used in node modules
Fix for issue [#1767](https://github.com/OwlCarousel2/OwlCarousel2/issues/1767)
> Allow package file to expose CSS

- src/js/owl.carousel.js
This change always removes left-over .center classes before checking if a new one should be set.
Otherwise, .center class can hang around when settings.center is set using responsive options (and responsive element changes size)
> .center class hangs around when responsive options

- docs_src/templates/pages/docs/dev-plugin-api.hbs
Without {}, "PluginName.Defaults" object is merged with "this.owl.options"
> Documentation : plugin api mistake

- src/js/owl.carousel.js
When `autoWidth` is enabled and there are no initial children, an error is thrown and the carousel becomes unusable.
> Fix empty child auto width

- src/js/owl.autoplay.js
- test/index.html
- test/unit/autoplay.js
This pull request proposes an improvement to the autoplay internal timing mechanism. It makes the autoplay plugin easier to understand and fixes #440/#993, #1038, #1179, #1426/#1727, #1464, #1471/#1620/#1827/#1860/#1911, #1518, #1655 and #1948. The pull request is an updated version of #1039 and works with the current state of the codebase.
- Resuming after a pause will make sure the time already elapsed before the pause will be subtracted from the new timeout. This also works when changing timeout values after resuming. 
- Animation timings can be changed on the fly (by calling `play` with the new `timeout` value). If the new timeout is shorter than the time already elapsed since the last animation, the carousel will animate instantly. If it is longer, the carousel will wait for the …
> Improving autoplay behavior

- src/js/owl.navigation.js
When destroying the owl carousel, there is a null pointer being thrown by Navigation.  The `settings` object is never declared [here](https://github.com/OwlCarousel2/OwlCarousel2/blob/a731e93393b9c60757bc94ccb9d946763127c3f2/src/js/owl.navigation.js#L229).
Relates to #1778
> Resolve null pointer with navigation destroy

- docs/docs/dev-plugin-api.html
Replaced the spelling of the word 'methods'.
> Fixed Typo

- docs/assets/owlcarousel/owl.carousel.js
- src/js/owl.autorefresh.js
- src/js/owl.carousel.js
Hey,
we love the OwlCarousel and have it heavily at use in production. On some pages up to 4 carousels at the same time.
The problem: On old android devices (like Galaxy S4/S5ish), DOM manipulation and forced reflows are very slow. And it get worse the more complex the page becomes.
With this PR we were able to reduce the render time of a page with 4 carousels from 10 seconds to 2,5 seconds on a Galaxy S4.
In this plunkr the difference is not that severe as its just a blank page and the items are simple text, but you already see the impact:
plunkr: http://plnkr.co/edit/c52107vIiWWNJDYPKJqV?p=preview
4 carousel ~ 100ms
plunkr: http://plnkr.co/edit/CSRUwANcqOgD4S7LAmDm?p=preview
4 carousel ~ 55ms
Instead of
```twig
<div class="owl-carousel owl-theme carousel-default">
<div class="item …
```
> allow faster bootstrap with less forced reflow and dom manipulation

- dist/owl.carousel.js
- src/js/owl.lazyload.js
This PR does allow lazy loading for source tags.
Example code:
```html
<html>
<head>
<link rel="stylesheet" href="https://owlcarousel2.github.io/OwlCarousel2/assets/owlcarousel/assets/owl.carousel.min.css">
<link rel="stylesheet" href="https://owlcarousel2.github.io/OwlCarousel2/assets/owlcarousel/assets/owl.theme.default.min.css">
<script type="text/javascript" src="https://owlcarousel2.github.io/OwlCarousel2/assets/vendors/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.rawgit.com/mimarcel/OwlCarousel2/fix/owl-lazy-for-source-tags/dist/owl.carousel.js"></script>
<script>
jQuery(function() {
jQuery('.owl-carousel').owlCarousel({
items: 1,
lazyLoad:true,
loop:true,
margin:10
});
});
</script>
</head>
<body>
<div class="owl-carousel owl-theme">
<picture>
<source …
```
> Allow lazy loading for source tags
