OwlCarousel2/OwlCarousel2

- docs_src/templates/pages/demos/lazyLoad.hbs
Found a spelling error and rather than post it on the issues I figured I'd updated it.
strucutre > structure
> Fixed a spelling mistake

- src/css/owl.animate.css
- src/js/owl.video.js
I required Vzaar support for a project so I added it - hopefully it'll be useful as a full addition.
Didn't require any risky changes so it should be stable. Tested on Firefox/FF-dev/Chrome on OSX.
> Add Vzaar video support

- src/scss/_mixins.scss
- src/scss/_theme.scss
- src/scss/owl.autoheight.scss
- src/scss/owl.lazyload.scss
- src/scss/owl.video.scss
Prefix common mixin names with "owl-". This helps to prevent mixin conflicts with other common mixin libraries such as Bourbon http://bourbon.io
> Prefix owl mixins to prevent conflicts with other mixin libraries

- src/js/owl.video.js
- Fixes mixed content errors for image thumbnails and videos when using the videos plugin
Fixes #931
> Removes mixed content errors by moving to protocol agnostic paths in video.js. Fixes #931

- docs_src/templates/pages/docs/started-installation.hbs
- docs_src/templates/pages/docs/started-welcome.hbs
* Styled the getting started section's next step links to be consistent with api section
> Styled getting started section's next step links 

- src/js/owl.carousel.js
> Fixes off-by-one error when using rtl and center options

- src/scss/owl.video.scss
> fix owl.video.css

- src/js/owl.carousel.js
choosing correct index to test whether pull distance exceeds threshold
> Fixing over-sensitive rightward swipe on touch devices

- docs_src/assets/scss/highlight.scss
FIRST:
SECOND:
THIRD:
this bags fixed!
> scroll bag fixed

- dist/owl.carousel.js
> Fixes a few spelling typos on documentation.

- bower.json
Tools like https://github.com/rquadling/bower-installer depend on this to include dist files
> Add owl.theme.default.css to bower main files

- docs_src/templates/pages/docs/dev-buildin-plugins.hbs
> Fix a typo

- Gruntfile.js
- src/js/owl.navigation.js
Fixed code style to pass jscs test
> Fix code style

- docs/docs/started-welcome.html
> fixed a typo

- src/scss/_video.scss
Correcting an error when compiling with Webpack : _Module not found: Error: Can't resolve './owl.video.play.png'_
This will also resolve this issue : https://github.com/OwlCarousel2/OwlCarousel2/issues/2107
> Added a new var to append to video-play image

- src/js/owl.carousel.js
Replaced the condition for checking the coordinate range
> fixes #2001

- src/js/owl.navigation.js
- update aria-label text to be readable
- add type to buttons
> close #1920 Accessibility tweaks

- src/scss/_video.scss
sass interpolate had wrong syntax
> fix scss interpolate for video-play image

- docs/docs/api-options.html
- docs_src/data/options.json
- description take from comment in code
> Add documentation for `checkVisible` option

- src/js/owl.video.js
Simplifies and changes the iframe HTML construction to use DOM node construction
Also fixes an error where mozallowfullscreen and webkitallowfullscreen wasn't being applied to youtube iframes
> Simplifies and changes the iframe HTML construction to use DOM node construction

- src/js/owl.carousel.js
Rewrite the stage element creation so that classes are added in a mor…e secure manner via DOM node construction
the stageElement is suboptimal but this is nonetheless an improvement
> Rewrite the stage element creation to use DOM node construction
